version: 0.0
os: linux

files:
  - source: webapp.zip
    destination: /home/ubuntu/webapp

hooks:
    
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
