name: Build and Deploy Artifact

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: webapp_v1
      CODE_DEPLOY_APPLICATION_NAME: csye6225_webApp
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225_webApp_deployment_group
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - run:
         npm install
      - name: Run Unit Tests
        run: npm run test