name: Build and Deploy Artifact

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: webapp_v1
      CODE_DEPLOY_APPLICATION_NAME: csye6225-webapp
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node 
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - run: 
         npm install
      - name: Run Unit Tests
        run: npm run test
      
      - name: Archive Releases
        run: |
          npm install
          zip -r webapp ./
          mkdir ./codedeploy_artifact
          zip -r ${{env.ARTIFACT_NAME}}  webapp.zip ./codedeploy/*.sh appspec.yml
          mv  ./${{env.ARTIFACT_NAME}}.zip ./codedeploy_artifact

      # - name: Install AWS CLI 2
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload artifact to s3
        run: aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_BUCKET_NAME}}

      - name: CodeDeploy API Call
        run: output=$(aws deploy create-deployment --application-name ${{env.CODE_DEPLOY_APPLICATION_NAME}} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} --description "CSYE6225 - CodeDeploy" --s3-location bucket=${{secrets.S3_BUCKET_NAME}},key=${{env.ARTIFACT_NAME}}.zip,bundleType=zip --region ${{secrets.AWS_REGION}} --output json)
              echo $output
              dID=$(echo $output | jq -r '.deploymentId')
              aws deploy wait deployment-successful --deployment-id $dID

        